# Generated by Django 2.2 on 2021-07-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0002_auto_20210715_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customerreading',
            unique_together={('customer', 'rate', 'number')},
        ),
    ]
