# Generated by Django 2.2 on 2021-07-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0004_auto_20210715_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('xlsx', models.FileField(upload_to='')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
