# Generated by Django 2.2 on 2021-07-15 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0005_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='xlsx',
            field=models.FileField(upload_to='', verbose_name='File'),
        ),
    ]
